/*
 * Selling Partner API for A+ Content Management
 *
 * Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.
 *
 * The version of the OpenAPI document: 2020-11-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContentType : The A+ Content document type.
/// The A+ Content document type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContentType {
    #[serde(rename = "EBC")]
    Ebc,
    #[serde(rename = "EMC")]
    Emc,
    #[serde(rename = "BrandStory")]
    BrandStory,
}

impl std::fmt::Display for ContentType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ebc => write!(f, "EBC"),
            Self::Emc => write!(f, "EMC"),
            Self::BrandStory => write!(f, "BrandStory"),
        }
    }
}

impl Default for ContentType {
    fn default() -> ContentType {
        Self::Ebc
    }
}

