/*
 * Selling Partner API for Orders
 *
 * Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use crate::models::string_bool::StringBool;
use serde::{Deserialize, Serialize};

/// AutomatedShippingSettings : Contains information regarding the Shipping Settings Automation program, such as whether the order's shipping settings were generated automatically, and what those settings are.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutomatedShippingSettings {
    /// When true, this order has automated shipping settings generated by Amazon. This order could be identified as an SSA order.
    #[serde(rename = "HasAutomatedShippingSettings", skip_serializing_if = "Option::is_none")]
    pub has_automated_shipping_settings: Option<StringBool>,
    /// Auto-generated carrier for SSA orders.
    #[serde(rename = "AutomatedCarrier", skip_serializing_if = "Option::is_none")]
    pub automated_carrier: Option<String>,
    /// Auto-generated ship method for SSA orders.
    #[serde(rename = "AutomatedShipMethod", skip_serializing_if = "Option::is_none")]
    pub automated_ship_method: Option<String>,
}

impl AutomatedShippingSettings {
    /// Contains information regarding the Shipping Settings Automation program, such as whether the order's shipping settings were generated automatically, and what those settings are.
    pub fn new() -> AutomatedShippingSettings {
        AutomatedShippingSettings {
            has_automated_shipping_settings: None,
            automated_carrier: None,
            automated_ship_method: None,
        }
    }
}

