/*
 * Selling Partner API for Orders
 *
 * Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use crate::models::string_bool::StringBool;
use serde::{Deserialize, Serialize};

/// ExceptionDates : Dates when the business is closed or open with a different time window.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExceptionDates {
    /// Date when the business is closed, in <a href='https://developer-docs.amazon.com/sp-api/docs/iso-8601'>ISO 8601</a> date format.
    #[serde(rename = "ExceptionDate", skip_serializing_if = "Option::is_none")]
    pub exception_date: Option<String>,
    /// Boolean indicating if the business is closed or open on that date.
    #[serde(rename = "IsOpen", skip_serializing_if = "Option::is_none")]
    pub is_open: Option<StringBool>,
    /// Time window during the day when the business is open.
    #[serde(rename = "OpenIntervals", skip_serializing_if = "Option::is_none")]
    pub open_intervals: Option<Vec<models::orders_v0::OpenInterval>>,
}

impl ExceptionDates {
    /// Dates when the business is closed or open with a different time window.
    pub fn new() -> ExceptionDates {
        ExceptionDates {
            exception_date: None,
            is_open: None,
            open_intervals: None,
        }
    }
}

